/*
 * This source file was generated by the Gradle 'init' task
 */
package ordering_system;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.SwingUtilities;
import javax.swing.Timer;

import ordering_system.Controller.OrderController;
import ordering_system.Controller.DashboardController;
import ordering_system.Dao.CustomerDao;
import ordering_system.Dao.OrderDao;
import ordering_system.Dao.ProductDao;
import ordering_system.Dao.SizeDao;
import ordering_system.Services.OrderService;
import ordering_system.View.MainFrame;
import ordering_system.View.CardArea.Dashboard.DashboardPanel;
import ordering_system.View.CardArea.Dashboard.MetricCardsPanel;
import ordering_system.View.CardArea.Order.CustomerInfoPanel;
import ordering_system.View.CardArea.Order.OrderInfoPanel;
import ordering_system.View.CardArea.Order.OrderPanel;
import ordering_system.View.CardArea.Order.OrderPanelBottom;
import ordering_system.View.CardArea.Order.OrderTable;
import ordering_system.View.CardArea.ViewOrder.ViewOrderPanel;

public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            MainFrame form = new MainFrame();
            form.setVisible(true);
            MetricCardsPanel metricCardsPanel = form.getMetricCardsPanel();
            ViewOrderPanel viewOrderPanel = form.getViewOrderPanel();
            OrderPanel orderPanel = form.getOrderPanel();
            OrderPanelBottom orderPanelBottom = orderPanel.getOrderPanelBottom();
            OrderInfoPanel orderInfoPanel = orderPanel.getOrderInfoPanel();
            CustomerInfoPanel customerInfoPanel = orderPanel.getCustomerInfoPanel();
            OrderTable orderTable = orderPanel.getOrderTable();
            OrderDao orderDao = new OrderDao();
            CustomerDao customerDao = new CustomerDao();
            ProductDao productDao = new ProductDao();
            SizeDao sizeDao = new SizeDao();
            OrderService orderService = new OrderService(orderDao, customerDao, productDao, sizeDao);
            OrderController orderController = new OrderController(orderPanelBottom, orderInfoPanel, customerInfoPanel, orderTable, orderService, orderDao, productDao, viewOrderPanel);
            DashboardController dashboardController = new DashboardController(metricCardsPanel, orderDao, orderService);
        });
    }
}
