/*
 * This source file was generated by the Gradle 'init' task
 */
package ordering_system;


import ordering_system.View.MainFrame;

public class App {

    public static void main(String[] args) {
        new MainFrame();
    }
}
